name: AWS Cloud Resume Deployment workflow file

on:
  workflow_dispatch:

  push:
    branches:
      - main

defaults:
  run: 
    shell: bash

jobs:
  deployment-job:
    name: deployment job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: aws configured credentials
        run: |
          aws configure list
      
      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: check terraform version and initialize providers
        run: |
          terraform --version
          cd infra
          terraform init
          
      - name: run terraform main.tf file
        run: |
          terraform plan
        
      
