name: AWS Cloud Resume Deployment workflow file

on:
  workflow_dispatch:

  push:
    branches:
      - main

defaults:
  run: 
    shell: bash

jobs:
  deployment-job:
    name: deployment job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  code-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        
