name: AWS Cloud Resume Deployment workflow file

on:
  workflow_dispatch:

  push:
    branches:
      - main

defaults:
  run: 
    shell: bash

jobs:
  deployment-job:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      run: |
      terraform init
